LibraryWebDb/Controllers/LibraryController.cs
using LibraryWebDb.Extensions;
using LibraryWebDb.Helpers;
using LibraryWebDb.Models;
using LibraryWebDb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LibraryWebDb.Controllers
{
	public class LibraryController : Controller
	{
		private readonly LibraryDbContext libraryDbContext;

		public LibraryController(LibraryDbContext libraryDbContext)
		{
			this.libraryDbContext = libraryDbContext;
		}

		[HttpGet]
		public IActionResult Index(int? categoryId, int? genreId, int page = 1)
		{
			var books = libraryDbContext.Books.Include(b => b.BookGenres).ThenInclude(bg => bg.Genre).Include(b => b.Category).OrderByDescending(b=>b.Id);

			if (categoryId != null)
			{
				books = (IOrderedQueryable<Book>)books.Where(b=>b.CategoryId == categoryId);
			}

            if (genreId != null)
            {
				//var bookArray = libraryDbContext.BookGenres.Where(bg=>bg.GenreId == genreId).Select(bg => bg.BookId);
				//books = (IOrderedQueryable<Book>)books.Where(b => bookArray.Contains(b.Id));
				books = (IOrderedQueryable<Book>)books.Where(b => b.BookGenres.Any(bg => bg.GenreId == genreId));
			}

			var model = new IndexViewModel();

			int totalP = (int)Math.Ceiling(books.Count() / (double)model.LimitPage);
			books = (IOrderedQueryable<Book>)books.Skip((page-1)*model.LimitPage).Take(model.LimitPage);


			model.Books = books;
			model.Categories = libraryDbContext.Categories;
			model.Genres = libraryDbContext.Genres;
			model.RecentBooks = libraryDbContext.Books.OrderByDescending(b => b.Id).Take(model.LimitPage);
			model.CurrentPages = page;
			model.TotalPages = totalP;
			model.SelectedCategoryId = categoryId;
			model.SelectedGenreId = genreId;
			

			return View(model);
		}

		[HttpGet]
		public IActionResult Add()
		{
			ViewBag.categories = new SelectList(libraryDbContext.Categories, "Id", "Name");
			ViewBag.genres = new MultiSelectList(libraryDbContext.Genres, "Id", "Name");
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Add(Book book, IFormFile Image, int[] genres)
	 	{
			
			book.ImageUrl = await FileUploadHelper.UploadAsync(Image);
			book.CreatedDate = DateTime.Now;
			await libraryDbContext.Books.AddAsync(book);
			await libraryDbContext.SaveChangesAsync();

			libraryDbContext.BookGenres.AddRange(genres.Select(g => new BookGenre() { BookId = book.Id, GenreId = g }));
            await libraryDbContext.SaveChangesAsync();

            return RedirectToAction("Index");
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var book = libraryDbContext.Books.Find(id);
			return View(book);
		}

		[HttpPost]
		[ActionName("Delete")]
		public async Task<IActionResult> ConfirmDelete(int id)
		{
			var book = libraryDbContext.Books.Find(id);
			libraryDbContext.Books.Remove(book);
			await libraryDbContext.SaveChangesAsync();
			TempData["status"] = "Книга удалена";
            return RedirectToAction("Index");
        }

		[HttpGet]
		public IActionResult Details(int id)
		{
			var book = libraryDbContext.Books
				.Include(b => b.BookGenres).ThenInclude(bg => bg.Genre)
				.Include(b => b.Category)
				.FirstOrDefault(b => b.Id == id);
			return View(book);
		}

		[HttpGet]
		public IActionResult Edit(int id)
		{
			var book = libraryDbContext.Books.Find(id);

			ViewBag.categories = new SelectList(libraryDbContext.Categories, "Id", "Name");

			var selectedGenresIds = libraryDbContext.BookGenres.Where(bg => bg.BookId == id).Select(bg => bg.GenreId);
			ViewBag.genres = new MultiSelectList(libraryDbContext.Genres, "Id", "Name", selectedGenresIds);
			return View(book);
		}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Book book, IFormFile Image, int[] genres)
        {
			if (Image != null)
			{
				var path = await FileUploadHelper.UploadAsync(Image);
				book.ImageUrl = path;
			}
			
			book.CreatedDate = DateTime.Now;
			libraryDbContext.Books.Update(book);
			await libraryDbContext.SaveChangesAsync();

			var bookWithGenres = libraryDbContext.Books.Include(b => b.BookGenres).FirstOrDefault(b => b.Id == book.Id);

			libraryDbContext.UpdateManyToMany(
				bookWithGenres.BookGenres,
				genres.Select(gId => new BookGenre { BookId = book.Id, GenreId = gId}),
				gId => gId.GenreId
				);
			await libraryDbContext.SaveChangesAsync();

            return RedirectToAction("Index");
		}
	}
}

LibraryWebDb/ViewComponents/PaginationViewComponent.cs
using LibraryWebDb.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LibraryWebDb.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int currentPage, int totalPages, int limit, int? genreId, int? categoryId)
        {
            PaginationViewModel paginationViewModel = new PaginationViewModel()
            {
                TotalPages = totalPages,
                CurrentPage = currentPage,
                PagesLimit = limit,
                GenreId = genreId,
                CategoryId = categoryId
            };
            return View("Pagination", paginationViewModel);
        }
    }
}

LibraryWebDb/Views/Library/Add.cshtml
@{
    ViewData["Title"] = "Add Book";
}

@model Book

<h1>Добавление</h1>

<form asp-asp-controller="Library" asp-action="Add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control"/>
        <span asp-asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        <span asp-asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label for="formFile" class="form-label">Загрузите обложку</label>
        <input class="form-control" type="file" name="Image" id="formFile">
    </div>

	<div class="form-group">
		<label asp-for="CategoryId"></label>
		<select asp-for="CategoryId" asp-items="ViewBag.categories" class="form-select" aria-label="Default select example">
		</select>
	</div>

    <div class="form-group">
        <label asp-for="BookGenres"></label>
        <select name="genres" asp-items="ViewBag.genres" multiple class="form-select chosen-select" aria-label="Default select example">
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" rows="8"></textarea>
        <span asp-asp-validation-for="Description" class="text-danger"></span>
    </div>

    <button class="btn btn-outline-primary w-25 mt-2">Add</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    @* tiny-text-editor library + chosen-multiselect*@
    <script src="https://cdn.tiny.cloud/1/nybgj490llrcmddyglqbrllp1hu21hpo1jmkoy7ukucdclwq/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        $(".chosen-select").chosen({no_results_text: "Oops, nothing found!" });

        tinymce.init({
          selector: 'textarea',
          plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
          toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
          tinycomments_mode: 'embedded',
          tinycomments_author: 'Author name',
          mergetags_list: [
            { value: 'First.Name', title: 'First Name' },
            { value: 'Email', title: 'Email' },
          ],
          ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
}

LibraryWebDb/Views/Library/Delete.cshtml
@model LibraryWebDb.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Удаление</h1>

<h3>Вы точно хотите удалить эту книгу?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete" asp-controller="Library" method="post">
        <input type="hidden" asp-for="Id" />
        <button class="btn btn-outline-danger">Удалить</button>
        <a asp-action="Index" asp-controller="Library" class="btn btn-outline-info">Назад в каталог</a>
    </form>
</div>

LibraryWebDb/Views/Library/Details.cshtml
@{
    ViewData["Title"] = "Details";
}

@model Book

<h1>Подробности</h1>

<div class="card">
    <img src="@Model.ImageUrl" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">@Model.Title</h5>
        <p class="card-text">@Model.Category.Name</p>
    </div>
    <ul class="list-group list-group-flush">
        @foreach (var item in @Model.BookGenres)
        {
            <li class="list-group-item">@item.Genre.Name</li>
        }
    </ul>
    <div class="card-body">
        <span class="card-link">@Html.Raw(@Model.Description)</span>
        <a asp-action="Index" asp-controller="Library" class="card-link">Назад</a>
    </div>
</div>

LibraryWebDb/Views/Library/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}

@model Book

<h1>Редактирование</h1>

<form asp-asp-controller="Library" asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Title"></label>
        <input asp-for="Title" class="form-control" />
        <span asp-asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" class="form-control" />
        <span asp-asp-validation-for="Author" class="text-danger"></span>
    </div>

    <input name="ImageUrl" asp-for="ImageUrl" hidden />
    <img src="@Model.ImageUrl" height="200"/>

    <div class="mb-3">
        <label for="formFile" class="form-label">Загрузите обложку</label>
        <input class="form-control" type="file" name="Image" id="formFile">
    </div>

    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" asp-items="ViewBag.categories" class="form-select" aria-label="Default select example">
        </select>
    </div>

    <div class="form-group">
        <label asp-for="BookGenres"></label>
        <select name="genres" asp-items="ViewBag.genres" multiple class="form-select chosen-select" aria-label="Default select example">
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control" rows="8"></textarea>
        <span asp-asp-validation-for="Description" class="text-danger"></span>
    </div>

    <button class="btn btn-outline-primary w-25 mt-2">Обновить</button>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />

    @* tiny-text-editor library + chosen-multiselect*@
    <script src="https://cdn.tiny.cloud/1/nybgj490llrcmddyglqbrllp1hu21hpo1jmkoy7ukucdclwq/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" });

        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | align lineheight | tinycomments | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            mergetags_list: [
                { value: 'First.Name', title: 'First Name' },
                { value: 'Email', title: 'Email' },
            ],
            ai_request: (request, respondWith) => respondWith.string(() => Promise.reject("See docs to implement AI Assistant")),
        });
    </script>
}

LibraryWebDb/Views/Library/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model IndexViewModel

@* @await Component.InvokeAsync("Pagination", new { currentPage = 1, totalPages = 1}) // alternative way*@ 
<vc:pagination current-page="@Model.CurrentPages"
			   total-pages="@Model.TotalPages"
			   limit="@Model.LimitPage"
			   genre-id="@Model.SelectedGenreId"
			   category-id="@Model.SelectedCategoryId"
			   action="Index" controller="Library"></vc:pagination>

<div class="col-2">
    <a asp-action="Index" asp-controller="Library" class="btn btn-outline-info">Сбросить</a>
    <div class="row">
        <h3>Категории</h3>
        <hr />
        <div class="list-group">
            @if (Model.Categories != null)
            {
                foreach (var item in Model.Categories)
                {
                    <a asp-action="Index" asp-controller="Library" asp-route-categoryId="@item.Id" asp-route-genreId="@Model.SelectedGenreId"
                    class="list-group-item list-group-item-action @(Model.SelectedCategoryId==item.Id ? "active" : ' ')">@item.Name</a>
                }
            }
        </div>
        <h3>Жанры</h3>
        <hr />
        <div class="list-group">
            @if (Model.Genres != null)
            {
                foreach (var item in Model.Genres)
                {
                    <a asp-action="Index" asp-conroller="Library" asp-route-genreId="@item.Id" asp-route-categoryId="@Model.SelectedCategoryId"
                    class="list-group-item list-group-item-action @(Model.SelectedGenreId==item.Id ? "active" : ' ')">@item.Name</a>
                }
            }
        </div>
    </div>
    
</div>
<div class="col-10">
    @if (Model.Books != null && Model.Books.Count() > 0)
    {
        <div class="row">
            @foreach (var item in Model.Books)
            {
                <div class="card col-4" style="width: 18rem;">
                    <img src="@item.ImageUrl" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <hr/>
						@if (item.BookGenres.Count() > 0)
						{
							@foreach (var bookGenre in item.BookGenres)
							{
								<span class="badge bg-primary rounded-pill">@bookGenre.Genre.Name</span>
							}
						}
						else
						{
							<span class="badge bg-danger rounded-pill">Нету</span>
						}
                        <hr/>
                        <strong>@item.Category.Name</strong><br/>
                        <p class="card-text">@item.Author</p>
                        <p class="card-text">@Html.Raw(@item.Description)</p>
                        <span>@item.CreatedDate</span>
                        <br>
                        <a asp-controller="Library" asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-success w-100">Подробнее</a>
                        <a asp-controller="Library" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-secondary w-100">Редактировать</a>
                        <a asp-controller="Library" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-danger w-100">Удалить</a>
                    </div>
                </div>
            }
        </div>
    }
    else if (@Model.Books.Count() == 0)
    {
        <h3>Ничего не найдено</h3>
    }
</div>